Bos 193
KaaschNicolas/Awp_Bosch pull request #50
Opened 2023-05-04 22:11 UTC by scda1092

Gibt es eine bessere Variante als das was in dem Main Window ein  und aus zukommentieren,  wenn man Test daten haben  möchte?

2023-05-05 13:30 UTC, arctix-tk commented
Ich würde vielleicht noch den DataService in MockDataService oder TestDataService umbennen damit das klarer wird für die Zukunft könnte ich mir noch vorstellen das wir den  Crud Service dann in DataService umbennen, da so wie es aussieht der CrudService bald nicht nur reine Crud-Operationen ausführen wird.

2023-05-11 10:40 UTC, fasa1016 requested changes
Aus meiner Sicht passt das soweit, aber wie du auch heute bereits erwähnt hast, durch BOS-234 wären nochmal Änderungen in _App.Core/Services/MockDataService.cs_ und _App/App.xaml.cs_ wichtig, siehe Kommentar zu den jeweiligen Dateien.

2023-05-11 10:40 UTC, fasa1016 commented on App.Core/Services/MockDataService.cs
1) Für "var path" in Zeile 22:
var path = Path.Combine(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location), @"Services\mockData");

2) Die Strings mittels "+" zu konkatenieren könnte zu Fehlern führen, nur ein Verbesserungsvorschlag wäre:
var fullPath = Path.Combine(path, "errorTypeMockData.json");
var file = File.ReadAllText(fullPath);

Aber an sich wäre nur Punkt 1) wichtig

2023-05-11 10:40 UTC, fasa1016 commented on App/App.xaml.cs
Ich würde vorschlagen, Änderungen in dieser Datei zu ignorieren und die Ergänzung aus Zeile 91 manuell im master hinzuzufügen, um einen Konflikt mit PR BOS-234 zu unterbinden.

2023-05-11 13:07 UTC, fasa1016 approved these changes
Danke dir!

2023-05-11 13:07 UTC, merged